### ISSUE TITLE
How to set source name?

### ISSUE THREAD

**Issue by gbmakaveli** [codetuner/Arebis.Logging.GrayLog#4]
Hi 

How to set source name?

Thanks

**Comment by codetuner** [comment]
Hi,
According to the GELF documentation, the "source" field is to be called "host":
http://docs.graylog.org/en/2.3/pages/gelf.html

The host is automatically set by the library to "Environment.MachineName".
(Line 53 of https://github.com/codetuner/Arebis.Common/blob/master/Arebis.Logging.GrayLog/GrayLogClient.cs)

I have adhered a strict interpretation of "host" being the "host", the "machine" and not another kind of source (application name, datacenter name, or other). Therefore, and because the "host" field is a mandatory "built-in" field of GELF, I have not foreseen a way to override it.

So you would have to change the code...

Alternatively, I suggest you keep the host/source as is (in my experience it is always handy to know the machine messages originated from, even if you have only one for now) and use an additional field "application" for instance, with the name of the application, and maybe "pid" with the Process ID. With HOST and PID you can then identify unambiguously the source process as long as it is still running.

Kind regards
Rudi Breedenraedt
